### PR TITLE
Rf power

### PR DESCRIPTION
**Pull request by serych**
I'm trying to **set more power and faster slewrate on RF output pins**. The code is working fine, but tomorrow I'll use osciloscope to inspect if it has any measurable effect. 
On that occasion **I pulled the code from main regarding GPIO settings into utilities.c.** **I also moved all #defines related to hardware into defines.h**. I hope this will make the code clearer and more readable.

Measurements have shown that the drive value and slew rate settings do not affect the output power. Therefore, the lines are commented out, but left in code for future investigation.

### CODE REVIEW

**Comment by EngineerGuy314** [comment]
Hi, could you verify quantitatively how much of a difference in power this generates? Also, how does it affect current consumption?

**Comment by serych** [comment]
Unfortunately, there is no difference between the default state (according to the datasheet PADS_BANK0_GPIO0_DRIVE_VALUE_4MA) and the PADS_BANK0_GPIO0_DRIVE_VALUE_12MA state. (applied to GPIO6 and 7)
A half-wave dipole for the 14.097 MHz band (length 10.12m) was connected to the pins. I connected the oscilloscope across 100nF capacitors (both live wire and ground) to separate the DC component and measure the floating signal (ground should be somewhere in the middle due to the pins operating in counterphase).  
I connected the oscilloscope with a 10:1 probe to reduce its effect on the signal.  
In the evening I will send pictures of both variants of the signal from the oscilloscope (I don't have the files on this computer I'm writing from).

I also measure the power supply current of the Pico (I power the GPS module separately to have data purely for the Pico).
At 135 MHz, about 26 mA flows into the Pico without transmitting, 33 mA when transmitting with the antenna connected, and about 30 mA when transmitting without the antenna connected. Also these currents are the same for both variants of the drive value. I only measure with a cheap Chinese multimeter, but I still expected at least some visible difference.

What has a visible effect is the slew rate setting. With the slow slew rate, the output signal is almost a flat line and only when the sensitivity of the oscilloscope input is increased, its ripple at 14 MHz can be seen. This proves that I am working with the correct registers that really affect the GPIO6 and 7 pins.

**Comment by serych** [comment]
Here are the osciloscope images, first 4mA, second 12mA drive. The signal is floating, so absolute values of voltages are irrelevant, but relative values are the same on both pictures. 
drive4mA
drive12mA

**Comment by serych** [comment]
I found out that my original pico had a non-functional GPIO6, so **my previous measurements are irrelevant**. 
I used a different pico plate and I can see signals on both two RF pins on the oscilloscope. I haven't made measurements with the antenna yet though.  
However, **I have added a new "Antenna tuning" feature** to this pull request, which allows you to enter the desired frequency in the menu and start force transmit.

**Pull request merged**
